on: push
name: Publish
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - name: Build
        run: nix build
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r result/* .
          rm -r result
          touch .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
